"""Puzzle and PuzzleSolutions table

Revision ID: 212e480d6150
Revises: 25dc25761cae
Create Date: 2026-01-09 13:47:35.057487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212e480d6150'
down_revision = '25dc25761cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fen', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_puzzle_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_puzzle_user_id'), ['user_id'], unique=False)

    op.create_table('puzzle_solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('puzzle_solution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_puzzle_solution_puzzle_id'), ['puzzle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_puzzle_solution_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_puzzle_solution_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle_solution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_puzzle_solution_user_id'))
        batch_op.drop_index(batch_op.f('ix_puzzle_solution_timestamp'))
        batch_op.drop_index(batch_op.f('ix_puzzle_solution_puzzle_id'))

    op.drop_table('puzzle_solution')
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_puzzle_user_id'))
        batch_op.drop_index(batch_op.f('ix_puzzle_timestamp'))

    op.drop_table('puzzle')
    # ### end Alembic commands ###
